# Docker compose for testing the database outside k8s cluster

services:
  postgres:
    container_name: consoleDB
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: jonathan
      POSTGRES_USER: postgres
      POSTGRES_DB: consoleDB
    ports:
      - "5432:5432"